version: '2'
services:
    web:
      build: .
      command: python -u app.py
      ports:
        - "80:80"
        - "8080:80"
      volumes:
        - ./src:/app
        - /tmp/cache
      environment:
        - SECOND_MASTER=localhost